AWSTemplateFormatVersion: 2010-09-09
Description: Docudata Base Platform common nodejs libraries layer
Transform:
- AWS::Serverless-2016-10-31
Resources:
  CommonLibsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: common-nodejs-libs-1
      Description: Dependencies for sam app [temp-units-conv]
      ContentUri: s3://docudata-be-sam-deploy-bucket/86bf7aadff8079b7406e327165e16bb0
      CompatibleRuntimes:
      - nodejs14.x
      LicenseInfo: MIT
      RetentionPolicy: Retain
